### ISSUE TITLE
Error: meteorhacks-npm.d.ts not found

### ISSUE THREAD

**Issue by bjimdar** [meteor-typescript/meteor-typescript-libs#36]
Receiving the error below at application startup after upgrading to 1.2.4:

```
=> Errors prevented startup:
   While building the application: 
   /opt/projects/vw1/zzz.ts-compiler.ts:1:1:

   /opt/projects/vw1/.meteor/local/build/programs/server/assets/packages/meteortypescript_typescript-libs/definitions/all-definitions.d.ts(17,1):

   error TS6053: File
   '/opt/projects/vw1/.meteor/local/build/programs/server/assets/packages/meteortypescript_typescript-libs/definitions/meteorhacks-npm.d.ts' not
   found.

```

Looks like commit [14c5fcd](https://github.com/meteor-typescript/meteor-typescript-libs/commit/4177e619d978136fa7ea6ae9a5b1165eaa70b134) add a reference to **meteorhacks-npm.d.ts** in **all-definitions.d.ts**, but I can't find it checked in anywhere.

**Comment by bjimdar** [comment]
My workaround for the time being is to just put an empty file in place of the file it's looking for.

```
touch .meteor/local/build/programs/server/assets/packages/meteortypescript_typescript-libs/definitions/meteorhacks-npm.d.ts

**Comment by mblaublomme** [comment]
it seem the file is always deleted automatically... ?

**Comment by fullflavedave** [comment]
I'll fix this issue this afternoon.

**Comment by bjimdar** [comment]
Thanks for all your hard work  @fullflavedave!
It's really great having his package.

**Comment by mblaublomme** [comment]
Thanks to you for this great meteor package !

**Comment by fullflavedave** [comment]
My pleasure.  Thank you all for finding the bugs, which is as important as fixing them!

**Comment by mblaublomme** [comment]
Last question :
Did you think to update the meteor package (added with "meteor add meteortypescript:typescript-libs") ?

It seem the meteorhacks file is not imported...

**Comment by fullflavedave** [comment]
Ack!  I obviously need a better test process for implementing changes, and I'll work on that next.  I'll add this to the package file contents shortly.

**Comment by fullflavedave** [comment]
Let me know if I finally got it right this time.

**Comment by dphilipson** [comment]
Thanks for your work on this package! Unfortunately, I'm still having the same problem in the latest version (1.2.7) when I use `meteor add meteortypescript:typescript-libs`.

**Comment by fullflavedave** [comment]
Sorry about all that.  Hopefully it works now.
