### ISSUE TITLE
Error rebuilding app after upgrading from 1.1.1 to 1.1.2

### ISSUE THREAD

**Issue by kctang** [meteor-typescript/meteor-typescript-libs#17]
After upgrade, I managed to start my Meteor app.

However, it gave me these errors when Meteor tries to rebuild the app after I edit some .ts files.

      While building the application:
      /Users/bob/test-project/zzz.ts-compiler.ts:1:1: 
      /Users/bob/test-project/.meteor/local/build/programs/server/assets/packages/meteortypescript_typescript-libs/definitions/node.d.ts(198,26): error TS2304: Cannot find
      name 'DataView'.
      /Users/bob/test-project/.meteor/local/build/programs/server/assets/packages/meteortypescript_typescript-libs/definitions/node.d.ts(212,21): error TS2304: Cannot find
      name 'Map'.
      /Users/bob/test-project/.meteor/local/build/programs/server/assets/packages/meteortypescript_typescript-libs/definitions/node.d.ts(221,21): error TS2304: Cannot find
      name 'Set'.
      /Users/bob/test-project/.meteor/local/build/programs/server/assets/packages/meteortypescript_typescript-libs/definitions/node.d.ts(231,25): error TS2304: Cannot find
      name 'WeakMap'.

Downgraded back to 1.1.1, the problem went away.

**Comment by fullflavedave** [comment]
Thanks for catching this!
