### ISSUE TITLE
Error "no exported member IdGenerationEnum" after upgrading to 1.1.10

### ISSUE THREAD

**Issue by bjimdar** [meteor-typescript/meteor-typescript-libs#30]
After upgrading to version 1.1.10 I'm getting this fatal error message on Meteor startup:

```
=> Your application has errors. Waiting for file change.
=> Modified -- restarting.
   Downloading missing packages              /
Compiling TypeScript os files...
   Building the application                  |
Compiling TypeScript web.browser files...
=> Errors prevented startup:

   While building the application:
   /opt/projects/typescript-libs-test/zzz.ts-compiler.ts:1:1:

   /opt/projects/typescript-libs-test/.meteor/local/build/programs/server/assets/packages/meteortypescript_typescript-libs/definitions/smart-collections.d.ts(14,24):
   error TS2305: Module 'Mongo' has no exported member 'IdGenerationEnum'.
```

Looks like 1.1.9 has a interface declaration for "IdGenerationEnum" in meteor.d.ts, but version 1.1.10 of the package (as submitted to Meteor yesterday) doesn't have it.

Can we get a bump to 1.1.11 with the most recent version of all files?

Thanks!

**Comment by fullflavedave** [comment]
Sorry about that.  I forgot to check that change in.  Will release 1.1.11 shortly.

**Comment by bjimdar** [comment]
Confirmed Closed. 
Upgraded to 1.1.11 and now I'm back in business.

Dude! 30 minutes is a pretty fast turn around for a fix. 
I feel like I should buy you a pizza or something.
:smile: :pizza:

**Comment by fullflavedave** [comment]
Glad it's working.  It's always easier to go back in when it's fresh in my head!  Thanks for catching and reporting that.
